name: Build and Deploy Code

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repository
        uses: actions/checkout@v3
      - name: Say hello
        run: echo "Hello, world!"
